GET http://localhost:4120/JSONAdminApi/AdminApi/AsTree/Json/UserFolders/ScreensFromDisplayJson/TableColumns/DataAttributes
Cookie: KToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyTmFtZSI6IkZJTjEiLCJEYXRhUGsiOjMwMSwiaWF0IjoxNjczMzU2ODIwfQ.mUb8zefVXuhPt-irgES-fGMEu-DaiAQLJZIZKfAdQKQ
content-type: application/json

{
}