POST http://localhost:4120/JSONUser/Validate/Users/InUserGroupsJson/ForUserNamePasswordFirm/LoginCheckReturnTokenOnly
content-type: application/json

{
       "inUserName":"K3",
        "inPassWord": "K3",
        "inFirmName": "Jasti Mallikharjunudu Sons & Co"
    }