POST http://localhost:4120/JSONUser/Validate/Users/InUserGroupsJson/ForUserNamePasswordFirm/LoginCheckReturnTokenOnly
Cookie: KToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyTmFtZSI6Ik5TUDIyMjMiLCJEYXRhUGsiOjEwMjQsImlhdCI6MTY3NTMzNTcwNn0.WIr0xfwgkUujXuDTZSz5Ge2QjBNe-scrd2PtbnIbfGw
content-type: application/json

{
       "inUserName":"NSP2223",
        "inPassWord": "NSP2223",
        "inFirmName": "KeshavSoft"
    }