POST http://localhost:4119/JSONApi/Validate/Users/InUserGroupsJson/ForUserNameAndPassword/TokenToCookie
Cookie: KToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyTmFtZSI6Ik1BR1VWQUEiLCJEYXRhUGsiOjkwMSwiaWF0IjoxNjg0MTQ3Mzc5fQ.iDia2YqACiE-LkcAnpmyE7L9qEHykAVQ-oDE-L0Wso8
content-type: application/json

{
    "inUserName": "JASTI", "inPassWord": "JASTI"

}