POST  http://localhost:4119/JSONApi/Validate/Users/InUserDataJson/ForUserNameAndPassword/TokenToCookieFirmDetailsAlso
Cookie: KToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyTmFtZSI6Ik1BR1VWQUEiLCJEYXRhUGsiOjkwMSwiaWF0IjoxNjg0MzIwNjk3fQ.ahndu8BTp1-3J0qXUSJR3yxae5OmKlk-KSEQ3hdTvmk
content-type: application/json


{
    "inUserName":"MAGUVAA"
}

