POST http://localhost:4119/JSONAdminApi/AdminApi/Utility/Json/FirmDetails/FromMsSql
Cookie: KToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyTmFtZSI6IkZJTjEiLCJEYXRhUGsiOjE3LCJpYXQiOjE2NzE3OTA5NjR9.Qx49axtwZlyDatSt14GybvE3mHEer3sgJiOJGFdHQp8
content-type: application/json

{
       "FirmName":"Keshav",
        "FromDate": "01-04-2020",
        "ToDate": "31-03-2021",
        "AssYear":"sssss",
        "FinYear":"ffffffff",
        "PAN":"ppppppp",
        "GST":"GGGGGGG"
    }